@startuml

left to right direction

actor "Користувач" as User
actor "Сервіс доставки" as Delivery

rectangle SafeFoodArt {

usecase "Авторизуватися" as UC1
usecase "Замовити їжу" as UC2
usecase "Отримати\nсповіщення" as UC3
usecase "Надіслати\nповідомлення" as UC4
usecase "Переглянути\nматеріали" as UC5

}

User --> UC1
User --> UC2
User --> UC3
User --> UC4
User --> UC5

Delivery --> UC2

UC2 .> UC1 : <<include>>

@enduml
