@startuml

class Користувач {
  idКористувача
  ім_я
  email
  пароль
}

class Замовлення {
  idЗамовлення
  дата
  статус
  сума
}

class ЗакладХарчування {
  idЗакладу
  назва
  адреса
  рейтинг
}

class Робота {
  idРоботи
  назва
  автор
  стиль
}

class Сповіщення {
  idСповіщення
  текст
  тип
  дата
}

Користувач "1" -- "*" Замовлення
ЗакладХарчування "1" -- "*" Замовлення
Користувач "*" -- "*" Робота
Користувач "1" -- "*" Сповіщення

@enduml
